FROM alpine:3.21
WORKDIR /app
RUN apk update && apk add ffmpeg
COPY ./_bin/linux-amd64 /app/ffmate
ENV PORT=3000
ENV DB=/app/db/sqlite.db
ENV DEBUGO=*
ENV LOGLEVEL=info
ENV MAX_CONCURRENT_TASKS=3
EXPOSE ${PORT}
RUN mkdir -p /app/db
CMD /app/ffmate server -p $PORT -d $DEBUGO -b $DB -l $LOGLEVEL -m $MAX_CONCURRENT_TASKS